DROP TABLE IF EXISTS PESSOAS CASCADE;
CREATE TABLE IF NOT EXISTS PESSOAS (
	PES_IDEN SERIAL,
	PES_NOME VARCHAR(50),
	PES_SOBRENOME VARCHAR(50), 
	PES_SEXO VARCHAR(20),
	PES_ENDERECO VARCHAR(100),
	PRIMARY KEY (PES_IDEN)
	);

/*
SELECT PES.* FROM PESSOAS PES;
INSERT INTO PESSOAS (PES_NOME, PES_SOBRENOME, PES_SEXO, PES_ENDERECO) VALUES ('JOAO', 'LINO', 'M', 'GYN - GO BR');
*/