DROP TABLE IF EXISTS PESSOAS CASCADE;
CREATE TABLE IF NOT EXISTS PESSOAS (
	PES_IDEN SERIAL,
	PES_NOME VARCHAR(50),
	PES_SOBRENOME VARCHAR(50), 
	PES_SEXO VARCHAR(20),
	PES_ENDERECO VARCHAR(100),
	PRIMARY KEY (PES_IDEN)
	);

DROP TABLE IF EXISTS LIVROS CASCADE;
CREATE TABLE IF NOT EXISTS LIVROS (
	LIV_IDEN SERIAL,
	LIV_TITULO VARCHAR(50),
	LIV_AUTOR VARCHAR(50), 
	LIV_DATA_LANCAMENTO DATE,
	LIV_PRECO NUMERIC(10,2),
	PRIMARY KEY (LIV_IDEN)
	);



INSERT INTO PESSOAS (PES_NOME, PES_SOBRENOME, PES_SEXO, PES_ENDERECO) VALUES ('JOAO', 'LINO', 'M', 'GYN - GO BR');
INSERT INTO PESSOAS (PES_NOME, PES_SOBRENOME, PES_SEXO, PES_ENDERECO) VALUES ('MARCIO', 'BALIAN', 'M', 'APGYN - GO BR');

INSERT INTO LIVROS (LIV_TITULO, LIV_AUTOR, LIV_DATA_LANCAMENTO, LIV_PRECO) VALUES ('O LIVRO MALUCO', 'JOHN NASH', '05-01-2020', 49.90);
INSERT INTO LIVROS (LIV_TITULO, LIV_AUTOR, LIV_DATA_LANCAMENTO, LIV_PRECO) VALUES ('APRENDA DOTNET EM 1 DIA', 'MALA MAN', '05-01-2021', 149.90);
